---
- name: Conexión a la API de Fortigate con Token
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Obtener direcciones firewall
      uri:
        url: "{{ fortigate_url }}"
        method: GET
        headers:
          Authorization: "Bearer {{ fortigate_token }}"
        validate_certs: no
      register: resultado

    - debug:
        var: resultado.json.results[0]
