---
- name: Conexión a la API de Fortigate con Token
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Creación de VLAN
      uri:
        url: "{{ fortigate_url }}"
        method: POST
        headers:
          Authorization: "Bearer {{ fortigate_token }}"
          Content-Type: "application/json"
        validate_certs: no
        body_format: json
        body:
          name: "{{ vlan_name }}"
          vdom: "{{ vdom }}"
          type: "{{ type_vlan }}"
          interface: "{{ physical_interface }}"
          vlanid: "{{ vlan_id }}"
          role: "{{ role }}"
          device-identification: "{{ device_identification }}"
          snmp-index: "{{ vlan_id }}"
          allowaccess: "{{ allow_access }}"
          alias: "{{ alias_name }}"
          vlan-protocol: "{{ vlan_protocol }}"
          status: "up"
          vlan_ip: "0.0.0.0/0.0.0.0"
      register: resultado

    - debug:
        var: resultado.json
